# Generated by Django 4.1.2 on 2022-10-30 11:40

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("details", models.TextField(max_length=1000)),
                (
                    "start_date",
                    models.DateTimeField(
                        default=datetime.datetime(2022, 10, 30, 11, 40, 47, 675962)
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        default=datetime.datetime(2022, 11, 29, 11, 40, 47, 675973)
                    ),
                ),
                (
                    "create_date",
                    models.DateTimeField(
                        verbose_name=datetime.datetime(2022, 10, 30, 11, 40, 47, 675981)
                    ),
                ),
                ("target", models.PositiveIntegerField()),
                (
                    "Category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="projects.category",
                    ),
                ),
                (
                    "project_creator",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
