# Generated by Django 4.1.2 on 2022-10-31 16:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0014_alter_project_create_date_alter_project_end_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="project_creator",
        ),
        migrations.AlterField(
            model_name="project",
            name="create_date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 10, 31, 16, 52, 40, 454186)
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="end_date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 11, 30, 16, 52, 40, 454179)
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="start_date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 10, 31, 16, 52, 40, 454172)
            ),
        ),
    ]
