# Generated by Django 4.1.2 on 2022-10-31 17:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0019_alter_project_create_date_alter_project_end_date_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="project_creator",
            new_name="project_create",
        ),
        migrations.AlterField(
            model_name="project",
            name="create_date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 10, 31, 17, 1, 45, 944268)
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="end_date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 11, 30, 17, 1, 45, 944262)
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="start_date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 10, 31, 17, 1, 45, 944256)
            ),
        ),
    ]
