# Generated by Django 4.1.2 on 2022-10-31 17:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0020_rename_project_creator_project_project_create_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="project_create",
        ),
        migrations.AlterField(
            model_name="project",
            name="create_date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 10, 31, 17, 6, 17, 813418)
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="end_date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 11, 30, 17, 6, 17, 813412)
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="start_date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 10, 31, 17, 6, 17, 813406)
            ),
        ),
    ]
