# Generated by Django 4.1.2 on 2022-10-31 19:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0023_alter_project_create_date_alter_project_end_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="create_date",
            field=models.DateTimeField(
                blank=True, default=datetime.datetime(2022, 10, 31, 19, 32, 25, 653434)
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="end_date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 11, 30, 19, 32, 25, 653427)
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="project_creator",
            field=models.ForeignKey(
                blank=True,
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="start_date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 10, 31, 19, 32, 25, 653419)
            ),
        ),
    ]
