# Generated by Django 4.1.2 on 2022-11-01 00:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0028_alter_donate_project_alter_donate_user_donated_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="total_donate",
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name="project",
            name="create_date",
            field=models.DateTimeField(
                blank=True, default=datetime.datetime(2022, 11, 1, 0, 12, 39, 729673)
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="end_date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 12, 1, 0, 12, 39, 729666)
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="start_date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 11, 1, 0, 12, 39, 729658)
            ),
        ),
    ]
