# Generated by Django 4.1.2 on 2022-11-01 02:25

import datetime
from django.db import migrations, models
import django.db.models.deletion
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0029_project_total_donate_alter_project_create_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="create_date",
            field=models.DateTimeField(
                blank=True, default=datetime.datetime(2022, 11, 1, 2, 25, 49, 891539)
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="end_date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 12, 1, 2, 25, 49, 891530)
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="start_date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 11, 1, 2, 25, 49, 891521)
            ),
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150, verbose_name=projects.models.Project
                    ),
                ),
                ("body", models.TextField()),
                (
                    "create_date",
                    models.DateTimeField(
                        blank=True,
                        default=datetime.datetime(2022, 11, 1, 2, 25, 49, 892346),
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comment",
                        to="projects.project",
                    ),
                ),
            ],
        ),
    ]
