# Generated by Django 4.1.2 on 2022-11-01 15:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0039_project_is_featured_alter_project_create_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="Category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="category",
                to="projects.category",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="create_date",
            field=models.DateTimeField(
                blank=True, default=datetime.datetime(2022, 11, 1, 15, 47, 28, 458289)
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="end_date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 12, 1, 15, 47, 28, 458282)
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="start_date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 11, 1, 15, 47, 28, 458275)
            ),
        ),
    ]
