# Generated by Django 4.1.2 on 2022-11-04 01:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0046_remove_project_images_alter_project_create_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="image",
            field=models.ImageField(
                default="media/media/istockphoto-913374922-612x612.jpg",
                null=True,
                upload_to="media/",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="create_date",
            field=models.DateTimeField(
                blank=True, default=datetime.datetime(2022, 11, 4, 1, 11, 24, 291293)
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="end_date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 12, 4, 1, 11, 24, 291287)
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="start_date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 11, 4, 1, 11, 24, 291280)
            ),
        ),
    ]
