# Generated by Django 4.1.2 on 2022-10-30 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="birth_day",
        ),
        migrations.AddField(
            model_name="profile",
            name="birthday",
            field=models.DateField(null=True),
        ),
    ]
