# Generated by Django 4.1.2 on 2022-10-30 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_remove_profile_birth_day_profile_birthday"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="birthday",
            field=models.DateTimeField(null=True),
        ),
    ]
