# Generated by Django 4.1.2 on 2022-10-31 01:32

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_alter_profile_birthday"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="birthday",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 10, 31, 1, 32, 19, 640652)
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="mobile_number",
            field=models.CharField(
                max_length=11,
                validators=[
                    django.core.validators.RegexValidator(
                        "^01[0-2][0-9]{8}$", "Egyptian Numbers only allowed"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="profile_pic",
            field=models.ImageField(blank=True, null=True, upload_to="media/"),
        ),
    ]
