# Generated by Django 4.1.2 on 2022-10-31 02:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_alter_profile_birthday_alter_profile_mobile_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="birthday",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 10, 31, 2, 19, 56, 568362)
            ),
        ),
    ]
